### ISSUE TITLE
Support for consistent hashing when initialising memcached servers

### ISSUE THREAD

**Issue by denisbr** [varnish/libvmod-memcached#2]
In large pools of memcached instances, using consistent hashing is highly preferable to avoid lookup misses when instances are removed or added. 

Having the option to specify serverlist like below would be very helpful in such scenarios:

```
memcached.servers("--SERVER=localhost --SERVER=anotherhost:12345 --DISTRIBUTION=consistent");
```

**Comment by fgsch** [comment]
This is a limitation in libmemcached. It will work in RHEL 7 but not in RHEL 6.

The option in RHEL 6 would be to add something akin memcached_behavior_set that can be used to change the distribution. That or backport a newer libmemcached ofc but not very keen on that route.

**Comment by daghf** [comment]
@denisbr, care to comment?

**Comment by denisbr** [comment]
@daghf If the server initialization works on newer libmemcached it's all good and this issue can be closed I think. (And from what I remember this is the case.)

**Comment by rezan** [comment]
Confirmed that this works as Denis expects.
