### ISSUE TITLE
cannot run make check with custom varnish path

### ISSUE THREAD

**Issue by dmatetelki** [varnish/libvmod-memcached#22]
i've installed varnish with `prefix=/opt/vc_419`

compiling is ok with:
`PKG_CONFIG_PATH=/opt/vc_419/lib/pkgconfig/ ./autogen.sh && PKG_CONFIG_PATH=/opt/vc_419/lib/pkgconfig/   ./configure && make -j 20`

but make check fails:

```
dmatetelki@denesx1c\:~/p/libvmod-memcached[autotools_fix*]$ make check
Making check in src
make[1]: Entering directory '/home/dmatetelki/p/libvmod-memcached/src'
Dvarnishd=/home/dmatetelki/bin/varnishd -Dvmod_topbuild=/home/dmatetelki/p/libvmod-memcached ../src/tests/test05.vtc
/bin/bash: -Dvmod_topbuild=/home/dmatetelki/p/libvmod-memcached: No such file or directory
Makefile:708: recipe for target '../src/tests/test05.vtc' failed
make[1]: [../src/tests/test05.vtc] Error 127 (ignored)
...
```

**Comment by dridi** [comment]
Normally you should do this:

```bash
export PKG_CONFIG_PATH=/opt/vc_419/lib/pkgconfig
export ACLOCAL_PATH=/opt/vc_419/share/aclocal
./autogen.sh
./configure
```

The `make check` failure happens because `check` doesn't depend on `all`, and I'm not interested in maintaining half-assed legacy makefiles.

Workaround: `make all && make check`

**Comment by dmatetelki** [comment]
thank you!
unfortunately it does not help
