### ISSUE TITLE
rename of event function not supported on varnish-6.0

### ISSUE THREAD

**Issue by ingvarha** [varnish/libvmod-memcached#26]
On branch 6.0-LTS, while compiling against varnish-6.0.5, make check reports
libvmod_memcached.so: undefined symbol: event

This is probably because the renaming of the event function in commit 35b731c is not supported before varnish-6.1.x.

Ingvar

**Comment by gquintard** [comment]
ah, I may have been a bit too quick on this changes, thank you for catching this, I'll handle it

**Comment by gquintard** [comment]
fixed in a7182d8034344f1ac3d8f433d75564a33abe3962, thanks @ingvarha
