### ISSUE TITLE
libvmod-memcached in production

### ISSUE THREAD

**Issue by darjisanket** [varnish/libvmod-memcached#27]
We planning to add a proxy layer in front of memcached nodes and make it easily scalable.
Our team is fan of Varnish and using it successfully from many years.
While searching I found out libvmod-memcached vmod and just want to know about anyone using it production and if you have any comparison metrics against other proxies like twemproxy, Mcrouter that would be great help.

**Comment by dridi** [comment]
Hello, it is definitely used in production, but I'm not aware of any comparison with any other tool in this space.
