### ISSUE TITLE
Add connection pooling

### ISSUE THREAD

**Issue by lkarsten** [varnish/libvmod-memcached#3]
Currently the VMOD sets up a separate memcached context per worker thread, and keeps it around until the thread is removed by Varnish.

Not necessarily all Varnish worker threads will use it, but the state is kept around anyway.

A possible optimization here is to do connection pooling, to use less resources both inside Varnish and on the memcached server.

**Comment by fgsch** [comment]
If we were to implement pooling we might want to consider a new vmod / interface since pooling will change things in a non-backward compatible way.

My ¥２
