### ISSUE TITLE
Problem importing -> 'libvmod_memcached.so: undefined symbol: memcached_free'

### ISSUE THREAD

**Issue by mromagnoli** [varnish/libvmod-memcached#4]
I'm with branch 3.0, I made it to install varnish module, but when I import it and use it I get this error:

```
Message from VCC-compiler:
Could not load module memcached
    /usr/lib/varnish/vmods/libvmod_memcached.so
    /usr/lib/varnish/vmods/libvmod_memcached.so: undefined symbol: memcached_free
('input' Line 7 Pos 8)
import memcached;
```

I also get this error executing **make check**.
Does anybody have had the same issue or could get me a clue?

**Comment by fgsch** [comment]
Please share the entire configure and make output.

**Comment by mromagnoli** [comment]
Complete output:
- for  [configure](http://paste.ubuntu.com/10828389/) 
- for [make](http://paste.ubuntu.com/10828400/)
- for [make install](http://paste.ubuntu.com/10828403/)
- for [make check](http://paste.ubuntu.com/10828407/)

My env vars are: 

```
LIBMEMCACHED_LIBS=/usr/local/lib
libvarnishapi_LIBS=/usr/local/src/varnish-3.0.2
LIBMEMCACHED_CFLAGS=-pipe
libvarnishapi_CFLAGS=-pipe
```

**Comment by fgsch** [comment]
LIBMEMCACHED_LIBS should contain the LDFLAGS equivalent, not the path to where the libraries are.
I'd suggest to let pkg-config do its work and don't define any environment variables.

**Comment by mromagnoli** [comment]
+1!
Thanks @fgsch ! This was driving me nuts!

**Comment by fgsch** [comment]
No prob. I will close this now.
