### ISSUE TITLE
Varnish needs to be restarted whenever the memcached pool changes and VCL is updated to reflect it

### ISSUE THREAD

**Issue by espebra** [varnish/libvmod-memcached#8]
Memcached connections (memcached_st) are created and binded to the current thread using pthread_setspecific(). If at some point you change in VCL the location of the Memcached server, you are forced to execute a restart of Varnish in order to refresh the already created connections. It would be nice to be able to do that just reloading the VCL. The suggestion here is using some kind of versioning increased every time init_function() is called. This approach is used in the Redis vmod (https://github.com/carlosabald e/libvmod-redis).

(Internal reference to feature request, RT#4939)

**Comment by rezan** [comment]
Fixed in 0.3
