### ISSUE TITLE
Doesn't build against V4.1

### ISSUE THREAD

**Issue by fgsch** [varnish/libvmod-memcached#9]
Via ingvar:

[ingvar@netcat ~/src/vmods/vmod-memcached]$ git clone https://github.com/varnish/libvmod-memcached.git
Cloning into 'libvmod-memcached'...
remote: Counting objects: 640, done.
remote: Total 640 (delta 0), reused 0 (delta 0), pack-reused 640
Receiving objects: 100% (640/640), 96.58 KiB | 0 bytes/s, done.
Resolving deltas: 100% (350/350), done.
Checking connectivity... done.

[ingvar@netcat ~/src/vmods/vmod-memcached]$ cd libvmod-memcached/

[ingvar@netcat ~/src/vmods/vmod-memcached/libvmod-memcached]$ ./autogen.sh && ./configure 
(...)

[ingvar@netcat ~/src/vmods/vmod-memcached/libvmod-memcached]$ make

make  all-recursive
make[1]: Entering directory '/rpl/home/ingvar/src/vmods/vmod-memcached/libvmod-memcached'
Making all in src
make[2]: Entering directory '/rpl/home/ingvar/src/vmods/vmod-memcached/libvmod-memcached/src'
/usr/share/varnish/vmodtool.py ../src/vmod_memcached.vcc
ERROR: Format error reading "../src/vmod_memcached.vcc": 'Unknown keyword: $Init'

Makefile:700: recipe for target 'vcc_if.h' failed
make[2]: **\* [vcc_if.h] Error 254
make[2]: Leaving directory '/rpl/home/ingvar/src/vmods/vmod-memcached/libvmod-memcached/src'
Makefile:513: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/rpl/home/ingvar/src/vmods/vmod-memcached/libvmod-memcached'
Makefile:381: recipe for target 'all' failed
make: **\* [all] Error 2

[ingvar@netcat ~/src/vmods/vmod-memcached/libvmod-memcached]$ rpm -q libmemcached-devel varnish-libs-devel
libmemcached-devel-1.0.18-4.fc22.x86_64
varnish-libs-devel-4.1.0-1.fc24.x86_64

**Comment by ingvarha** [comment]
Adding this simple patch, the module compiles, but the test crashes:

```
diff --git a/src/vmod_memcached.vcc b/src/vmod_memcached.vcc
index 0e84428..70ed920 100644
--- a/src/vmod_memcached.vcc
+++ b/src/vmod_memcached.vcc
@@ -1,5 +1,5 @@
-$Module memcached 3
-$Init init_function
+$Module memcached 3 Memcached VMOD
+$Event init_function
 $Function VOID servers(PRIV_VCL, STRING)
 $Function VOID error_string(PRIV_VCL, STRING)
 $Function VOID pool_timeout_msec(PRIV_VCL, INT)
```

Result:
    **\*  v1    0.7 debug| Assert error in VRT_handling(), cache/cache_vrt.c line 239:\n
    **\*  v1    0.7 debug|   Condition((ctx)->magic == 0x6bb8f0db) not true.\n

Full build output of make check: https://gist.github.com/ingvarha/cf8425e5105f54d4df7c

**Comment by rezan** [comment]
Is this because of 4.1???

Edit: just read the title :)

**Comment by fgsch** [comment]
Yes.

You cannot simply replace Init with Event, the code needs to be updated.

**Comment by rezan** [comment]
I upgraded the VMOD to 4.1 having it load via VCL_EVENT_LOAD. The door is open for pool optimizations around the other VCL_EVENT_*. I create a 4.0 branch at a6052d24b1096cfd7c39ad7691721b182f2436fe.
